export enum BackgroundColorCode {
  primary = 'primary',
  primary_subtle = 'primary-subtle',
  secondary = 'secondary',
  secondary_subtle = 'secondary-subtle',
  success = 'success',
  success_subtle = 'success-subtle',
  danger = 'danger',
  danger_subtle = 'danger-subtle',
  warning = 'warning',
  warning_subtle = 'warning-subtle',
  info = 'info',
  info_subtle = 'info-subtle',
  light = 'light',
  light_subtle = 'light-subtle',
  dark = 'dark',
  dark_subtle = 'dark-subtle',
  body_secondary = 'body-secondary',
  body_tertiary = 'body-tertiary',
  body = 'body',
  black = 'black',
  white = 'white',
  transparent = 'transparent',
}