
// 🔴🟠🟡🟢🔵🟣🟤⚫⚪🟥🟧🟨🟩🟦🟪🟫⬛⬜
export enum PlayerCode {
  X = "❌",
  O = "⭕",
  Tick = "✔",
  CircleRed = "🔴",
  CircleOrange = "🟡",
  CircleYellow = "🔴",
  CircleGreen = "🟢",
  CircleBlue = "🔵",
  CirclePurple = "🟣",
  CircleBrown = "🟤",
  CircleBlack = "⚫",
  CircleWhite = "⚪",
  SquareRed = "🟥",
  SquareOrange = "🟧",
  SquareYellow = "🟨",
  SquareGreen = "🟩",
  SquareBlue = "🟦",
  SquarePurple = "🟪",
  SquareBrown = "🟫",
  SquareBlack = "⬛",
  SquareWhite = "⬜",
}